baseURL = "http://xinuo.jnk.ink/"

title = "价格表"
theme = "hugo-book"
# Book configuration
disablePathToLower = true
enableGitInfo = true

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

# Multi-lingual mode config
# There are different options to translate files
# See https://gohugo.io/content-management/multilingual/#translation-by-filename
# And https://gohugo.io/content-management/multilingual/#translation-by-content-directory






[params]
# 黑暗模式
  BookTheme = 'dark'
# 留言板
  BookComments = true
# 翻译
  BookTranslatedOnly = true
